//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupProject_Web.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SysUser", Namespace="http://schemas.datacontract.org/2004/07/GroupProjectServices")]
    [System.SerializableAttribute()]
    public partial class SysUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateofbirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RegDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Dateofbirth {
            get {
                return this.DateofbirthField;
            }
            set {
                if ((this.DateofbirthField.Equals(value) != true)) {
                    this.DateofbirthField = value;
                    this.RaisePropertyChanged("Dateofbirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegDate {
            get {
                return this.RegDateField;
            }
            set {
                if ((this.RegDateField.Equals(value) != true)) {
                    this.RegDateField = value;
                    this.RaisePropertyChanged("RegDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTypeField, value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/GroupProjectServices")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProdCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProdDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ProdDiscountPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProdIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProdImgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProdNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ProdPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProdQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProdStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProdCategory {
            get {
                return this.ProdCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdCategoryField, value) != true)) {
                    this.ProdCategoryField = value;
                    this.RaisePropertyChanged("ProdCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProdDescription {
            get {
                return this.ProdDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdDescriptionField, value) != true)) {
                    this.ProdDescriptionField = value;
                    this.RaisePropertyChanged("ProdDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ProdDiscountPrice {
            get {
                return this.ProdDiscountPriceField;
            }
            set {
                if ((this.ProdDiscountPriceField.Equals(value) != true)) {
                    this.ProdDiscountPriceField = value;
                    this.RaisePropertyChanged("ProdDiscountPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProdId {
            get {
                return this.ProdIdField;
            }
            set {
                if ((this.ProdIdField.Equals(value) != true)) {
                    this.ProdIdField = value;
                    this.RaisePropertyChanged("ProdId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProdImg {
            get {
                return this.ProdImgField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdImgField, value) != true)) {
                    this.ProdImgField = value;
                    this.RaisePropertyChanged("ProdImg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProdName {
            get {
                return this.ProdNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdNameField, value) != true)) {
                    this.ProdNameField = value;
                    this.RaisePropertyChanged("ProdName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ProdPrice {
            get {
                return this.ProdPriceField;
            }
            set {
                if ((this.ProdPriceField.Equals(value) != true)) {
                    this.ProdPriceField = value;
                    this.RaisePropertyChanged("ProdPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProdQuantity {
            get {
                return this.ProdQuantityField;
            }
            set {
                if ((this.ProdQuantityField.Equals(value) != true)) {
                    this.ProdQuantityField = value;
                    this.RaisePropertyChanged("ProdQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProdStatus {
            get {
                return this.ProdStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdStatusField, value) != true)) {
                    this.ProdStatusField = value;
                    this.RaisePropertyChanged("ProdStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        GroupProject_Web.ServiceReference1.SysUser Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        System.Threading.Tasks.Task<GroupProject_Web.ServiceReference1.SysUser> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UserReg", ReplyAction="http://tempuri.org/IService1/UserRegResponse")]
        int UserReg(GroupProject_Web.ServiceReference1.SysUser u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UserReg", ReplyAction="http://tempuri.org/IService1/UserRegResponse")]
        System.Threading.Tasks.Task<int> UserRegAsync(GroupProject_Web.ServiceReference1.SysUser u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getDOTW", ReplyAction="http://tempuri.org/IService1/getDOTWResponse")]
        GroupProject_Web.ServiceReference1.Product[] getDOTW();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getDOTW", ReplyAction="http://tempuri.org/IService1/getDOTWResponse")]
        System.Threading.Tasks.Task<GroupProject_Web.ServiceReference1.Product[]> getDOTWAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getProducts", ReplyAction="http://tempuri.org/IService1/getProductsResponse")]
        GroupProject_Web.ServiceReference1.Product[] getProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getProducts", ReplyAction="http://tempuri.org/IService1/getProductsResponse")]
        System.Threading.Tasks.Task<GroupProject_Web.ServiceReference1.Product[]> getProductsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : GroupProject_Web.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<GroupProject_Web.ServiceReference1.IService1>, GroupProject_Web.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GroupProject_Web.ServiceReference1.SysUser Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<GroupProject_Web.ServiceReference1.SysUser> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public int UserReg(GroupProject_Web.ServiceReference1.SysUser u) {
            return base.Channel.UserReg(u);
        }
        
        public System.Threading.Tasks.Task<int> UserRegAsync(GroupProject_Web.ServiceReference1.SysUser u) {
            return base.Channel.UserRegAsync(u);
        }
        
        public GroupProject_Web.ServiceReference1.Product[] getDOTW() {
            return base.Channel.getDOTW();
        }
        
        public System.Threading.Tasks.Task<GroupProject_Web.ServiceReference1.Product[]> getDOTWAsync() {
            return base.Channel.getDOTWAsync();
        }
        
        public GroupProject_Web.ServiceReference1.Product[] getProducts() {
            return base.Channel.getProducts();
        }
        
        public System.Threading.Tasks.Task<GroupProject_Web.ServiceReference1.Product[]> getProductsAsync() {
            return base.Channel.getProductsAsync();
        }
    }
}
